#!/usr/bin/env ruby

require "vesta"

# v = Vesta::API.new('user-name')
# puts v.add_database('asd', 'aa')
# puts v.methods
# puts v.normalize
# puts v.add_task ["nn", "ddf"]
first_arg, *the_rest = ARGV
v = Vesta::API.new
# d = v.dasherize.to_s
# vesta =  Vesta::API.start(d)
v.start
# v.v_add_backup_ftp_host
puts v.v_list_users(first_arg)
# puts "v.#{first_arg} #{the_rest}"
# puts v.("s")
