#!/usr/bin/env ruby

require "vesta"

# v = Vesta::API.new('user-name')
# puts v.add_database('asd', 'aa')
# puts v.methods
# puts v.normalize
# puts v.add_task ["nn", "ddf"]
v = Vesta::API.new
# d = v.dasherize.to_s
# vesta =  Vesta::API.start(d)
v.start
# v.v_add_backup_ftp_host
puts v.v_delete_cron_vesta_autoupdate(["asd", "uj"])
puts v.v_delete_cron_vesta_autoupdate("s")
